<definitions targetNamespace="http://eu.tennet.helloworldservice" 
             name="HelloWorldService" 
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
             xmlns:tns="http://eu.tennet.helloworld" 
             xmlns:svc="http://eu.tennet.helloworldservice" 
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns="http://schemas.xmlsoap.org/wsdl/">
	<types>
		<xsd:schema>
			<xsd:import namespace="http://eu.tennet.helloworld" schemaLocation="../xsd/Helloworld.xsd"/>
		</xsd:schema>
	</types>
	<message name="sayHelloOneWay">
		<part name="parameters" element="tns:sayHelloOneWay"/>
	</message>
	<portType name="HelloWorldService">
		<operation name="sayHelloOneWay">
			<input message="svc:sayHelloOneWay"/>
		</operation>
	</portType>
</definitions>